// src/routes/LandingPage.svelte
<script lang="ts">
  import { DeliveryError } from "@kontent-ai/delivery-sdk";
  import HeroImage from "../components/HeroImage.svelte";
  import PageContent from "../components/PageContent.svelte";
  import PageSection from "../components/PageSection.svelte";
  import "../index.css";
  import type { LandingPage } from "../model";
  import { createClient } from "../utils/client";
  import { appConfig } from "../lib/stores/app.svelte";
  import type { Replace } from "../utils/types";
  import FeaturedContent from "../components/FeaturedContent.svelte";
  import Layout from "../components/Layout.svelte";
  import SolutionListItem from "../components/SolutionListItem.svelte";

  let landingPage = $state<Replace<LandingPage, { elements: Partial<LandingPage["elements"]> }> | null>(null);
  let loading = $state(true);

  $effect(() => {
    createClient(appConfig.environmentId, appConfig.apiKey)
      .items()
      .type("landing_page")
      .limitParameter(1)
      .toPromise()
      .then(res => {
        landingPage = res.data.items[0] as Replace<LandingPage, { elements: Partial<LandingPage["elements"]> }> ?? null;
        loading = false;
      })
      .catch((err) => {
        if (err instanceof DeliveryError) {
          landingPage = null;
        } else {
          throw err;
        }
        loading = false;
      });
  });
</script>

<Layout>
  {#if loading}
    <div class="grow flex items-center justify-center">
      <div class="animate-spin border-solid border-8 border-[#f3f3f3] rounded-full border-t-burgundy w-32 h-32"></div>
    </div>
  {:else if !landingPage || !Object.entries(landingPage.elements).length}
    <div class="grow"></div>
  {:else}
    <div class="grow">
      <PageSection color="bg-creme">
        <HeroImage
          data={{
            headline: landingPage.elements.headline,
            subheadline: landingPage.elements.subheadline,
            heroImage: landingPage.elements.hero_image,
          }}
        />
      </PageSection>
      <PageSection color="bg-white">
        <SolutionListItem />
      </PageSection>
      {#if landingPage.elements.body_copy}
        <PageSection color="bg-white">
          <PageContent body={landingPage.elements.body_copy} />
        </PageSection>
      {/if}
      {#if landingPage.elements.featured_content}
        <FeaturedContent featuredContent={landingPage.elements.featured_content} />
      {/if}
    </div>
  {/if}
</Layout>

// src/pages/LandingPage.tsx
import { DeliveryError } from "@kontent-ai/delivery-sdk";

import HeroImage from "../components/HeroImage";
import PageContent from "../components/PageContent";
import PageSection from "../components/PageSection";
import "../index.css";
import { type LandingPage } from "../model";
import { createClient } from "../utils/client";
import { useSuspenseQueries } from "@tanstack/react-query";
import { FC } from "react";
import { useAppContext } from "../context/AppContext";
import { Replace } from "../utils/types";
import FeaturedContent from "../components/FeaturedContent";
import Layout from "../components/Layout";
import SolutionList from "../components/SolutionListItem";

const LandingPage: FC = () => {
  const { environmentId, apiKey } = useAppContext();

  const landingPage = useSuspenseQueries({
    queries: [
      {
        queryKey: ["landing_page"],
        queryFn: () =>
          createClient(environmentId, apiKey)
            .items()
            .type("landing_page")
            .limitParameter(1)
            .toPromise()
            .then(res =>
              res.data.items[0] as Replace<LandingPage, { elements: Partial<LandingPage["elements"]> }> ?? null
            )
            .catch((err) => {
              if (err instanceof DeliveryError) {
                return null;
              }
              throw err;
            }),
      },
    ],
  })[0];

  if (!landingPage.data || !Object.entries(landingPage.data.elements).length) {
    return (
      <Layout>
        <div className="grow" />
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="grow">
        <PageSection color="bg-creme">
          <HeroImage
            data={{
              headline: landingPage.data.elements.headline,
              subheadline: landingPage.data.elements.subheadline,
              heroImage: landingPage.data.elements.hero_image,
            }}
          />
        </PageSection>
        <PageSection color="bg-white">
          <SolutionList />
        </PageSection>
        {landingPage.data.elements.body_copy && (
          <PageSection color="bg-white">
            <PageContent body={landingPage.data.elements.body_copy} />
          </PageSection>
        )}
        {landingPage.data.elements.featured_content && (
          <FeaturedContent featuredContent={landingPage.data.elements.featured_content} />
        )}
      </div>
    </Layout>
  );
};

export default LandingPage;
